name: pyproprox 
type: python:3.10

web:
  commands:
    start: "gunicorn -b $PORT app.py:app"
  locations:
    "/":
      root: ""
      passthru: true
      allow: false
    "/static":
      root: "static/"
      allow: true

hooks:
  build: |
    pip install -r requirements.txt
    pip install -e .
    pip install gunicorn

mounts:
  "/tmp": "shared:files/tmp"
  "/logs": "shared:files/logs"


disk: 128
